name: Build and test

on:
  # push:
  #   branches:
  #     - feature/git-action
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ vars.DB_DATABASE }}
          POSTGRES_USER: ${{ vars.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_pgsql, pgsql

      # - name: Copy .env
      #   run: cp src/.env.testing src/.env

      - name: Install app
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist
      
      - name: Clear Laravel config
        working-directory: ./src
        env:
          APP_ENV: testing
        run: php artisan config:clear

      - name: Check DB configuration
        working-directory: ./src
        env:
          APP_ENV: testing
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
        run: |
          echo "APP_ENV=$APP_ENV"
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_DATABASE=$DB_DATABASE"
          echo "DB_USERNAME=$DB_USERNAME"
      
      - name: Run migrations
        working-directory: ./src
        env:
          APP_ENV: testing
          DB_CONNECTION: pgsql
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate
      

      - name: Test PHPStan
        working-directory: ./src
        run: ./vendor/bin/phpstan analyse

      - name: Test PHPUnit
        working-directory: ./src
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./vendor/bin/phpunit